### ISSUE TITLE
Guide Ideas

### ISSUE THREAD

**Issue by Pdzly** [fedecan-ca/fedecan.ca#12]
In this issue i would like to collect all the guides that are planned so there isnt any double work.

**Comment by Pdzly** [comment]
I am planing to do a guide on alternative UIs.

**Comment by cynber** [comment]
I've opened up discussions if that is better. You may be able to convert this issue into a discussion

**Comment by Pdzly** [comment]
https://github.com/fedecan-ca/fedecan.ca/discussions/15
